apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 980901e8-24f0-42e2-8c5f-946fe5a2a073
  creationTimestamp: null
  labels:
    app: hello
  name: hello
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  strategy:
    canary:
      canaryService: hello-canary
      stableService: hello
      steps:
      - setWeight: 70
      - pause:
          duration: 120
      trafficRouting:
        ambassador:
          mappings:
          - hello
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: 8081,8022,6001
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
      - image: docker.io/datawire/hello-world:latest
        name: hello
        ports:
        - containerPort: 8000
          name: http
        resources: {}
status:
  blueGreen: {}
  canary: {}
